### PR TITLE
Fix tests + enable CI

### PR DESCRIPTION
**Pull request by dumbbell**
Before I start to work on and submit the actual change I'm interested in, I wanted to make sure the testsuite was successfull for me.

In this pull request, I made all the changes required to make `rebar3 eunit` and `rebar3 dialyzer` happy. In particular:
* Paths to files and directories in the testcases are relative to the project root directory.
* `bbmustache` is used to render templates.

While here, I added a Travis CI configuration. Here is the result for this branch:
https://travis-ci.com/rabbitmq/cuttlefish

Test coverage is also published to coveralls.io:
https://coveralls.io/github/rabbitmq/cuttlefish

This would allow you to add badges such as:
* [Build Status](https://travis-ci.com/rabbitmq/cuttlefish)
* [Coverage Status](https://coveralls.io/github/rabbitmq/cuttlefish)
* [Hex version](https://hex.pm/packages/cuttlefish)

### CODE REVIEW

**Comment by michaelklishin** [comment]
@Licenser sorry to bother you with mentions but is this fork still maintained?

**Comment by michaelklishin** [comment]
@tsloughter sorry to bother you with mentions but is this fork still maintained?

**Comment by tsloughter** [comment]
@michaelklishin not by me. Maybe @Licenser wants to continue maintaining it, I haven't talked to him in a while.

It is likely best for some users of cuttlefish to get together on a new fork (or better yet, get access to the repo in the bash org). I know vernemq is using it, I handed off the rebar3 cuttlefish plugin to them. Ping @larshesel

**Comment by michaelklishin** [comment]
@tsloughter how can we get access to the Basho fork?

**Comment by Licenser** [comment]
Heya, sorry for the slow reply, despite years of trying github notifications still elude me.

As tristan said, not actively but I don't mind merging changes or giving you access to it (if @tsloughter has no objections.).

**Review by Licenser — APPROVED** [review]
👍

**Comment by dumbbell** [comment]
Thank you!

**Comment by michaelklishin** [comment]
@Licenser our team would definitely appreciate the permissions to this repo and perhaps hex.pm. @dumbbell @lukebakken @acogoluegnes @dcorbacho and myself should be enough for now. Thank you!

**Comment by Licenser** [comment]
Invitations send.

**Comment by dumbbell** [comment]
Thanks! Invitation for GitHub received and accepted :-)

**Comment by dumbbell** [comment]
Could you please add us to the Hex.pm  package as well?

Our usernames there are:
* dumbbell
* gerhard
* michaelklishin
* rabbitmq

**Comment by Licenser** [comment]
all set

**Comment by dumbbell** [comment]
Awesome! That was fast :-)

**Pull request merged**
