### PR TITLE
Remove warnings_as_errors flag

### PR DESCRIPTION
**Pull request by ghost**
I'd rather have a build with warnings than fork 20 repositories to get a working build

### CODE REVIEW

**Comment by ghost** [comment]
Lol. Slight exaggeration. Need more coffee. Still would be nice to see it go. 
[failure.to.compile.no_slides.txt](https://github.com/Kyorai/cuttlefish/files/2039366/failure.to.compile.no_slides.txt)

**Comment by Licenser** [comment]
I disagree `warnings_as_errors` is a very sensible flag that enforces code quality. Removing it is the equivalent to setting `acculimiate_more_technical_debt` flag.

**Comment by Licenser** [comment]
Not to mention that the log fails at poolboy which isn't even part of cuttlefish.

**Comment by michaelklishin** [comment]
@Licenser @dumbbell currently compilation on OTP 22 fails because of a warning in Lager 3.6.3. Are warnings in dependencies really a reason to ruin someone else's app build?

**Comment by dumbbell** [comment]
Is there a way with Rebar to tell it to use `warnings_as_errors` only for the project, not dependencies? Because I find this option very useful for codebase I'm working on.

**Comment by michaelklishin** [comment]
There seem to be examples of just that that [use overrides](https://www.rebar3.org/docs/configuration).

**Comment by michaelklishin** [comment]
Lets close this for now as short term OTP 20+ compatibility issues in dependencies were addressed. We are open to reconsidering this if needed.

**Pull request closed without merging**
