### PR TITLE
Let's not lock it down to specific Elixir version

### PR DESCRIPTION
**Pull request by ghost**
More hassle than it's worth, also currently 0 Elixir projects using it. Let's have the minimum constraints. Should never have specified the Elixir version.

### CODE REVIEW

**Comment by ghost** [comment]
ta @Licenser

**Comment by Licenser** [comment]
👍 tagged as `2.1.1`

**Comment by ghost** [comment]
@Licenser - check your tags - tagged at 2.1.0

**Comment by Licenser** [comment]
https://github.com/Kyorai/cuttlefish/tree/v2.1.1 (the rebar3 hex tagging is a bit borken :( )

**Comment by Licenser** [comment]
oh I should have said `v2.1.1`

**Pull request merged**
